### ISSUE TITLE
Get upstream things updated for CBOR support

### ISSUE THREAD

**Issue by mvollrath** [osrf/rvizweb#13]
Post #12 we want to use official releases of upstream things instead of forks.

* [x] Fix eventemitter2 conflicts in [ros3djs](https://github.com/RobotWebTools/ros3djs/pull/245) and [roslibjs](https://github.com/RobotWebTools/roslibjs/pull/310).
* [x] [Get roslibjs released](https://github.com/RobotWebTools/roslibjs/pull/314).
* [x] [Get ros3djs released](https://github.com/RobotWebTools/ros3djs/pull/246) with both of the above changes.
* [x] [Fix lack of Polymer 1 support in ros-websocket](https://github.com/jstnhuang/ros-websocket/issues/2).
* [x] Get [ros-websocket](https://github.com/osrf/polymer-ros-websocket/pull/2) released with above changes.
* [x] Get [ros-service](https://github.com/osrf/polymer-ros-service/pull/1) released with above ros-websocket release.
* [x] Get [polymer-ros-rviz](https://github.com/osrf/polymer-ros-rviz/pull/19) released with above ros3djs, ros-websocket and ros-service changes.
* [x] Change this project to use above polymer-ros-rviz release and merge.

**Comment by chapulina** [comment]
For the polymer code, let's use our forks for now. @mvollrath , mind creating PRs with the necessary changes against these repos?

* https://github.com/osrf/polymer-ros-websocket
* https://github.com/osrf/polymer-ros-service
* https://github.com/osrf/polymer-ros-rviz

**Comment by mvollrath** [comment]
* https://github.com/osrf/polymer-ros-websocket/pull/1
* https://github.com/osrf/polymer-ros-service/pull/1
* https://github.com/osrf/polymer-ros-rviz/pull/18

**Comment by jubeira** [comment]
I went through the list and I checked that all those items were already solved. Closing now.
