### ISSUE TITLE
Installing inside a docker

### ISSUE THREAD

**Issue by athackst** [osrf/rvizweb#21]
I'm having trouble building this package within a docker on jenkins.  Could you provide a simple dockerfile that installs this properly?

**Comment by athackst** [comment]
FYI, Jenkins was having an issue because it wants to run docker images with its own user name and group.  Since nvm is a per user/per session thing and the initial set up was done inside the docker (but being this package was built with exec) Jenkins couldn't access nodejs.  Interestingly, instead of failing out on not being able to find node, it just didn't execute the execute_process steps (with no error output) and then would complain on install for the www directory not being present.

**Comment by jubeira** [comment]
Thanks for the report @athackst. 
- EDIT: is this problem happening now, or was this the original problem?
- Is it possible for you to share a reduced version of your Jenkinsfile for us to reproduce the problem?
- For my own understanding, are you using the [docker image in the repository](https://github.com/osrf/rvizweb/blob/master/docker/Dockerfile) as-is, or as part of a bigger Dockerfile in jenkins?

**Comment by athackst** [comment]
It was the original problem.  I've since just decided to pull and build as a part of the docker image as opposed to with the rest of my code.

Related: are you planning on releasing this in kinetic/melodic?  I would have just installed it if that were an option.

**Comment by jubeira** [comment]
As we already figured in #25, releasing it for Melodic might be a bit tricky until the dependencies are rolled out.

For Kinetic it should be possible; we would need to create the `-release` repository for that and maybe a `kinetic` branch here. @chapulina WDYT?

**Comment by chapulina** [comment]
Let's move the conversation about releasing into Kinetic to #27.

**Comment by jubeira** [comment]
Sounds good; closing this one then.
