### ISSUE TITLE
Image disappears when minimized

### ISSUE THREAD

**Issue by athackst** [osrf/rvizweb#28]
The image viewer disappears when the config element is minimized even though the image has been popped out of the side bar.

![Peek 2019-03-18 16-00](https://user-images.githubusercontent.com/6098197/54569201-261f8500-4997-11e9-823b-fd538f4742f3.gif)

**Comment by chapulina** [comment]
Fixed in https://github.com/osrf/polymer-ros-rviz/pull/23
