### ISSUE TITLE
catkin_make install failed

### ISSUE THREAD

**Issue by heshiwen1989** [osrf/rvizweb#45]
When I run "catkin_make install", I got the follow information: 

`added 1559 packages from 1717 contributors and audited 1354 packages in 14991.309s
found 936 vulnerabilities (910 low, 8 moderate, 18 high)
  run `npm audit fix` to fix them, or `npm audit` for details

┌────────────────────────────────────────────────────────┐
│                npm update check failed                 │
│          Try running with sudo or get access           │
│          to the local update config store via          │
│ sudo chown -R $USER:$(id -gn $USER) /home/hsw1/.config │
└────────────────────────────────────────────────────────┘

> rvizweb@0.0.0 build /media/hsw1/Document/rvizWeb/build/rvizweb/www
> bower install --allow-root && polymer build --name www

/media/hsw1/Document/rvizWeb/build/rvizweb/www/node_modules/bower/lib/node_modules/configstore/index.js:54
				throw err;
				^

Error: EACCES: permission denied, open '/home/hsw1/.config/configstore/bower-github.json'
You don't have access to this file.

    at Object.openSync (fs.js:443:3)
    at Object.readFileSync (fs.js:343:35)
    at Configstore.get (/media/hsw1/Document/rvizWeb/build/rvizweb/www/node_modules/bower/lib/node_modules/configstore/index.js:35:26)
    at new Configstore (/media/hsw1/Document/rvizWeb/build/rvizweb/www/node_modules/bower/lib/node_modules/configstore/index.js:28:45)
    at readCachedConfig (/media/hsw1/Document/rvizWeb/build/rvizweb/www/node_modules/bower/lib/config.js:19:23)
    at defaultConfig (/media/hsw1/Document/rvizWeb/build/rvizweb/www/node_modules/bower/lib/config.js:11:12)
    at Object.<anonymous> (/media/hsw1/Document/rvizWeb/build/rvizweb/www/node_modules/bower/lib/index.js:16:32)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rvizweb@0.0.0 build: `bower install --allow-root && polymer build --name www`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the rvizweb@0.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/hsw1/.npm/_logs/2020-12-21T17_26_16_727Z-debug.log
-- Configuring done
-- Generating done
-- Build files have been written to: /media/hsw1/Document/rvizWeb/build
####
####
Install the project...
-- Install configuration: ""
-- Installing: /media/hsw1/Document/rvizWeb/install/_setup_util.py
-- Installing: /media/hsw1/Document/rvizWeb/install/env.sh
-- Installing: /media/hsw1/Document/rvizWeb/install/setup.bash
-- Installing: /media/hsw1/Document/rvizWeb/install/local_setup.bash
-- Installing: /media/hsw1/Document/rvizWeb/install/setup.sh
-- Installing: /media/hsw1/Document/rvizWeb/install/local_setup.sh
-- Installing: /media/hsw1/Document/rvizWeb/install/setup.zsh
-- Installing: /media/hsw1/Document/rvizWeb/install/local_setup.zsh
-- Installing: /media/hsw1/Document/rvizWeb/install/.rosinstall
-- Installing: /media/hsw1/Document/rvizWeb/install/lib/pkgconfig/rvizweb.pc
-- Installing: /media/hsw1/Document/rvizWeb/install/share/rvizweb/cmake/rvizwebConfig.cmake
-- Installing: /media/hsw1/Document/rvizWeb/install/share/rvizweb/cmake/rvizwebConfig-version.cmake
-- Installing: /media/hsw1/Document/rvizWeb/install/share/rvizweb/package.xml
-- Installing: /media/hsw1/Document/rvizWeb/install/share/rvizweb/launch
-- Installing: /media/hsw1/Document/rvizWeb/install/share/rvizweb/launch/rvizweb.launch
CMake Error at rvizweb/cmake_install.cmake:56 (file):
  file INSTALL cannot find
  "/media/hsw1/Document/rvizWeb/build/rvizweb/www/build/www".
Call Stack (most recent call first):
  cmake_install.cmake:134 (include)

`

**Comment by srujan-aris** [comment]
I have the same issue. Were you able to resolve it?

**Comment by srujan-aris** [comment]
@heshiwen1989 ,

I have the same issue. Were you able to resolve this?

**Comment by heshiwen1989** [comment]
> @heshiwen1989 ,
> 
> I have the same issue. Were you able to resolve this?

For Me, Just Delete This  File: '/home/hsw1/.config/configstore/bower-github.json',  Because this file need root And Restart catkin_make install again !
